### PR TITLE
added purge count

### PR DESCRIPTION
**Pull request by nixnord**
Users will be able to purge `n` number of messages (from the replied message) by providing the message count in `/purge` command: `/purge [n]`.
Edit: this implementation has been tested in an instance of wbb deployed locally

### CODE REVIEW

**Review by TheHamkerCat — CHANGES_REQUESTED** [review]
Doesn't work properly, deletes unwanted messages

Also, format your code properly

**Comment by nixnord** [comment]
uh wdym "deletes unwanted messages"? There's one issue though, if the message IDs are non contiguous, the replied-to message and the sent message get deleted

**Comment by TheHamkerCat** [comment]
> uh wdym "deletes unwanted messages"? There's one issue though, if the message IDs are non contiguous, the replied-to message and the sent message get deleted

Deploy this version and invite your bot in [this](https://t.me/ProgrammersHubWithoutRules) chat, let me show you

**Comment by nixnord** [comment]
okie

**Review by nixnord — COMMENTED** [review]
done

**Review by TheHamkerCat — APPROVED** [review]

**Pull request merged**
