### PR TITLE
Add Crypto Module

### PR DESCRIPTION
**Pull request by jusidama18**

### CODE REVIEW

**Comment by TheHamkerCat** [comment]
Fix deepsource errors

**Review by TheHamkerCat — CHANGES_REQUESTED** [review]
The commits are there, and you're adding the feature on your own, so no need to give credits.

**Comment by annihilatorrrr** [comment]
async def crypto(_, message):

**Comment by TheHamkerCat** [comment]
> async def crypto(_, message):

Yeah, this one too, because we aren't actually using "client" in the function body

**Review by TheHamkerCat — APPROVED** [review]

**Pull request merged**
